Downgrade the rules_apple version to 3.5.1 from 3.8.0
* 3.5.1 or later results build failure of universal binary.

https://github.com/google/mozc/actions/runs/10538246849/job/29200541576

```
ERROR: /Users/runner/work/mozc/mozc/src/gui/about_dialog/BUILD.bazel:109:26: in macos_application rule //gui/about_dialog:about_dialog_macos:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_runner/70589f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/macos_rules.bzl", line 397, column 41, in _macos_application_impl
		processor_result = processor.process(
	File "/private/var/tmp/_bazel_runner/70589f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/processor.bzl", line 759, column 38, in _process
		_bundle_post_process_and_sign(
	File "/private/var/tmp/_bazel_runner/70589f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/processor.bzl", line 577, column 38, in _bundle_post_process_and_sign
		_bundle_partial_outputs_files(
	File "/private/var/tmp/_bazel_runner/70589f76e9298332e2e2764a78cc063e/external/rules_apple~/apple/internal/processor.bzl", line 347, column 29, in _bundle_partial_outputs_files
		fail(
Error in fail: Multiple files would be placed at "AboutDialog.app/Contents/Frameworks/QtCore" in the bundle, which is not allowed. check input file:
bazel-out/darwin_x86_64-opt-macos-x86_64-min11.0-applebin_macos-ST-0ef80d6acb6e/bin/_solib_darwin_x86_64/_U_A_A_Umain~_Urepo_Urules~qt_Umac_S_S_CQtCore_Umac___Ulib_SQtCore.framework/QtCore
ERROR: /Users/runner/work/mozc/mozc/src/gui/about_dialog/BUILD.bazel:109:26: Analysis of target '//gui/about_dialog:about_dialog_macos' failed
```
PiperOrigin-RevId: 667439926