Support Android build for Bzlmod.
* Added `oss_android_bzlmod` config to build Android lib with Blzmod.
  + e.g. `bazel build --config oss_android_bzlmod package`
* Tested with NDK r27. The former versions may not work.
* The current implementation always requires the ANDROID_NDK_HOME envvar even for non-Android builds.
  + This will be addressed in following CLs.
* https://github.com/google/mozc/issues/1002

Note, although --android_platforms supports multiple platforms,
Abseil doesn't support it yet, and requires the --cpu option.
As the result, it is not possibl to build both cpus with a single command.

When multiple platforms are specified, Abseil build fails with the following error.

```
ERROR: .../external/abseil-cpp~/absl/random/internal/BUILD.bazel:344:11: Compiling absl/random/internal/randen_hwaes.cc failed: (Exit 1): clang failed: error executing CppCompile command (from target @@abseil-cpp~//absl/random/internal:randen_hwaes_impl) external/rules_android_ndk~~android_ndk_repository_extension~androidndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -no-canonical-prefixes '--target=aarch64-linux-android31' -fdiagnostics-color ... (remaining 114 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang: error: unsupported option '-maes' for target 'aarch64-linux-android31'
clang: error: unsupported option '-msse4.1' for target 'aarch64-linux-android31'
```

It comes from `absl/copts/configure_copts.bzl`
* https://github.com/abseil/abseil-cpp/blob/20240722.0/absl/copts/configure_copts.bzl#L78

PiperOrigin-RevId: 664647967