Also specify `ABSL_CONST_INIT` in `com_implements.cc`
This is a follow up to 2d4b215c27e7b40092711a883c3b6c5b49ada5c0.

`ABSL_CONST_INIT` needs to be specified to both declaration and definition. Otherwise the build will fail with the following message when `/std:c++20` is specified.

```
error C2475: 'mozc::win32::com_implements_internal::com_module_ref_count': redefinition; 'constinit' specifier mismatch
```

#codehealth

PiperOrigin-RevId: 547397948